env:
  browser: true
  es6: true
extends:
  - plugin:prettier/recommended
rules:
  comma-dangle:
    - error
    - never
  import/prefer-default-export: off
  max-len:
    - error
    - code: 90
  newline-before-return: error
  no-param-reassign:
    - error
    - props: true
  no-return-assign: off
  no-unused-vars: error
