arrowParens: avoid
bracketSpacing: true
endOfLine: lf
htmlWhitespaceSensitivity: css
insertPragma: false
jsxBracketSameLine: false
jsxSingleQuote: true
printWidth: 90
proseWrap: preserve
quoteProps: as-needed
# rangeEnd: Infinity
rangeStart: 0
requirePragma: false
semi: true
singleQuote: true
tabWidth: 2
trailingComma: none
useTabs: false
