extends:
  - stylelint-config-standard
  - stylelint-prettier/recommended
  - stylelint-config-sass-guidelines
  - stylelint-config-rational-order
plugins:
  - stylelint-scss
rules:
  function-parentheses-space-inside: never-single-line
  max-nesting-depth: 5
  order/properties-alphabetical-order: null
  selector-pseudo-element-colon-notation: single
