extends:
  - stylelint-config-standard
  - stylelint-prettier/recommended
  - stylelint-config-sass-guidelines
  - stylelint-config-rational-order
plugins:
  - stylelint-scss
rules:
  max-nesting-depth: 3
  order/properties-alphabetical-order: null
  selector-pseudo-element-colon-notation: single
